#!/bin/sh

APP_DIR="/Applications/ChargeLimiter.app"
CACHE="/var/mobile/Library/Preferences/com.chargelimiter.mod.containerpath"

case "$1" in
    remove|purge)
        rm -f "$CACHE"
        ;;
esac

uicache -p "$APP_DIR" 2>/dev/null

exit 0
